### ISSUE TITLE
Enhance the beginner experience with simple steps on getting started

### ISSUE THREAD

**Issue by krook** [Call-for-Code/ClusterDuck-Protocol#106]
**Overview**
As more people join the community, it's good to be able to get them engaged as soon as possible. Whether that's by adding a demo video or overview showing how things work, or by creating short tutorials with simulated pieces (like using Paho to send MQTT messages that are later shown on their own DMS Lite, or by showing how to receive and interpret a message). The goal would be for them to be able to use the technology or contribute to it very quickly.

**Additional context**
After Call for Code submissions end on July 31, we'd like to provide IBM Developer visitors to go explore and contribute to previous projects that are now open source. They should be able to use the tech, or clearly see how they might open an issue or submit a pull request for basic improvements.

**Comment by TimoWielink** [comment]
We are currently working hard on rewriting the Quick Start to get started with the CDP. I and @knouse1344 are working on an instruction video that should be a good addition to how to build a Duck.

**Comment by nfeuer** [comment]
This could be an option? 

[ESP32 Simulator](https://github.com/mireq/esp32-simulator)

**Comment by krook** [comment]
Would love your feedback on what can be done to improve the experience @Evilgeniusnerd @trentbrown13 and others.

**Comment by nfeuer** [comment]
Maybe we can make some beginner projects? Build your own weather station?

**Comment by nfeuer** [comment]
- Quick start guide video of a powerpoint presentation
- Make a list of project ideas available on the website
- More youtube videos

**Comment by Evilgeniusnerd** [comment]
We have two scripts and documentation covering this one https://github.com/amirna2/ClusterDuck-Docs/blob/master/cdp-install-osx.sh. and another https://github.com/Code-and-Response/ClusterDuck-Protocol/wiki/Linux-CDP-Dev-Setup

**Comment by knouse1344** [comment]
videos drafted, will share videos in next couple days

**Comment by knouse1344** [comment]
working thru an improved variant of this

**Comment by krook** [comment]
Looks like there's been a lot of great documentation added to the wiki!
