### ISSUE TITLE
DishDuck Hybrid Inconsistency Issues 

### ISSUE THREAD

**Issue by Evilgeniusnerd** [Call-for-Code/ClusterDuck-Protocol#107]
**Describe the bug**
I have been doing testing on the DishDuck Hybrid this past week. I have found multiple issues as a result of this testing that needs to be fixed.  First is the "Hybrid Portion" when you are out of range of WiFi Rockblock is suppose to send the messages, Well I tested this and while it does work it is really inconsistent. Meaning that it does not always switch from one to the other. The second issue is that if the DishDuck is flashed without an SSID and Password, You should be able to goto PAPA Duck WiFi setup and set one. But that does not work at all as of right now get a watchdog error and TTgo T-Beam just reboots. Also (SSID Available Scan and Connect) hangs pretty often not allowing the T-Beam to carry on with operations.  

This is the WatchDog error when trying to use PAPA WiFi Setup Page
![screenshot_from_2020-07-13_18-20-44](https://user-images.githubusercontent.com/24256643/87465212-40e12880-c5e2-11ea-8542-f6637f965ef7.png)

**Comment by knouse1344** [comment]
so it appears after network scan or network(s) identification.  must be some configuration switching back and forth?  potentially serial turns off other components?  Amir's new PR [here](https://github.com/Code-and-Response/ClusterDuck-Protocol/pull/131) helps to show how we could more simply switch components (WiFi to serial to satcom, or something like that).  @Evilgeniusnerd let's play with this next couple days?

**Comment by amirna2** [comment]
Do we think this is an setup/configuration issue or some logic problem in the CDP Protocol?
The DuckBuilder is only helpful in the setup part of the duck and doesn't affect any implementation logic.
I'd like to get a bit more familiar with this `DishDuck Hybrid` duck.

**Comment by knouse1344** [comment]
We're not sure yet.  we can narrow down with more testing.  It happens when the DishDuck detects it has lost wifi network connectivity, then it automatically switches to satellite connection.  When attempting to switch back the error occurs.  might be some configuring or something more fundamental to the firmware/electronics.

**Comment by TimoWielink** [comment]
Seems to be working better with latest changes on Duck-Components

**Comment by Evilgeniusnerd** [comment]
Yes, this can be closed out now. It has successfully been switching between WiFi and Sat-Comm perfectly without any issue.
