### ISSUE TITLE
add comments to all functions

### ISSUE THREAD

**Issue by mkinney** [Call-for-Code/ClusterDuck-Protocol#11]
**Is your feature request related to a problem? Please describe.**
Add comments to all functions. Bonus points if they are doxygen-compatible.

**Describe the solution you'd like**
Add/format comments on each function in ClusterDuck code.

**Describe alternatives you've considered**
Doxygen-based formatting is probably the best option, but might consider using something like https://www.sphinx-doc.org

**Additional context**
Start small. Add comments and some auto-doc gen stuff.

**Comment by krook** [comment]
This is being addressed partially in this [work in progress](https://github.com/Code-and-Response/ClusterDuck-Protocol/pull/37) pull request.

**Comment by nfeuer** [comment]
This has been added with the Doxygen update
