### ISSUE TITLE
Readme says version is 2.1.6 but latest release is 2.0.4

### ISSUE THREAD

**Issue by amirna2** [Call-for-Code/ClusterDuck-Protocol#180]
**Describe the bug**
Most likely a typo. The version at the bottom of the README says 2.1.6, but latest release is 2.0.4

**To Reproduce**
See the README on the master branch

**Expected behavior**
Version should say 2.0.4

**Comment by TimoWielink** [comment]
We are currently at 2.1.6 but we have not made an official release for all the patches. @nfeuer we should make more releases based on minor changes.

https://github.com/Call-for-Code/ClusterDuck-Protocol/wiki/release-versions

**Comment by nfeuer** [comment]
Will be better about being on top of updating versions and releases in the future!
