### ISSUE TITLE
Add info on how to troubleshoot

### ISSUE THREAD

**Issue by mkinney** [Call-for-Code/ClusterDuck-Protocol#19]
**Is your feature request related to a problem? Please describe.**
After you create a MamaDuck, what should you see in Arduino Serial Monitor? (using 115200 baud)
After you create a PapaDuck, what should you see in Arduino Serial Monitor?

**Describe the solution you'd like**
Document some "errors"/problems.
Be sure to change the "Z" in the MamaDuck to a realistic value. (I used mac address without colons and it seemed to work ok.) If not, then you may see Authentication errors on PapaDuck serial output. 
If only see "i", check four values in PapaDuck. 

**Describe alternatives you've considered**
Add some troubleshooting/helpful info.

**Additional context**
Show info on what you should see on IBM side.

**Comment by mkinney** [comment]
This is what I see on PapaDuck serial output: (with some values obscured)

```
Serial start
LoRa On

Connecting to MYSSID..............................................................<snip>........................................................................................................................................................................................................................................
WiFi connected - PAPA ONLINE
PAPA Online
Reconnecting client to XXX.messaging.internetofthings.ibmcloud.com
136
User ID: 246f28b54624
Message ID: a8j:bkx4
Message: D6ju2LNqIyqq*Mike**None*1234567890*false*false*false*false*false*false*false*false*0*0*0*0*None*
Path: 246f28b54624
{
  "DeviceID": "246f28b54624",
  "MessageID": "a8j:bkx4",
  "Payload": "D6ju2LNqIyqq*Mike**None*1234567890*false*false*false*false*false*false*false*false*0*0*0*0*None*",
  "path": "246f28b54624,Papa"
}Publish ok
{
  "DeviceID": "246f28b54624",
  "MessageID": "a8j:bkx4",
  "Payload": "D6ju2LNqIyqq*Mike**None*1234567890*false*false*false*false*false*false*false*false*0*0*0*0*None*",
  "path": "246f28b54624,Papa"
}
```

**Comment by mkinney** [comment]
This is what I see on MamaDuck serial output:

```
Serial start
Created Hotspot
Created local DNS
LoRa On
MamaDuck Online
data received
Mike
Portal data received
wQ2JshY7fp0x*Mike**None*1234567890*false*false*false*false*false*false*false*false*0*0*0*0*None*
Here7
Packet sent
Message Sent
data received
Mike
Portal data received
wQ2JshY7fp0x*Mike**None*1234567890*false*false*false*false*false*false*false*false*0*0*0*0*None*
Here7
Packet sent
Message Sent
```

**Comment by mkinney** [comment]
If you visit your dashboard: https://XXX.internetofthings.ibmcloud.com/dashboard/devices/browse. (change XXX to your IBM Org)

For instance: https://ex7n1d.internetofthings.ibmcloud.com/dashboard/devices/browse

Looks like this:
<img width="1562" alt="Screen Shot 2020-03-14 at 8 53 55 AM" src="https://user-images.githubusercontent.com/2219838/76685511-9aecc580-65d1-11ea-940a-1af00bbf6411.png">

**Comment by mkinney** [comment]
Where should this info be captured/shared?

**Comment by knouse1344** [comment]
this is good stuff @mkinney .  Maybe would be best on like an FAQ / help page?  What do you think?  Slack is great for active conversations, but needs to be a place for documented things people can refer to.

**Comment by mkinney** [comment]
Sure. A "doc" folder could be created and some markdown could go in there (like "faq.md" or "troubleshooting.md")

Could also use the github wiki functionality. Up to you how you want to do it.

I think a lot of the readme could be moved there, too.

**Comment by knouse1344** [comment]
got it.  will get @TimoWielink on this.

**Comment by krook** [comment]
Thoughts on this @TimoWielink?

**Comment by nfeuer** [comment]
@TimoWielink you should revisit this while you are working on the Wiki

**Comment by TimoWielink** [comment]
Add more to FAQ page, with recent bugs and problems we have found.
