### ISSUE TITLE
DuckRadio doesn't need a member variable for `err`

### ISSUE THREAD

**Issue by rolsen** [Call-for-Code/ClusterDuck-Protocol#223]
DuckRadio.h declares a member `int err;`, but it's only used in DuckRadio::setupRadio and it's assigned to immediately.

Pretty minor but it was confusing. Quick to fix.

**Comment by amirna2** [comment]
Yep!
The local rc variable should be used instead.

**Comment by krook** [comment]
Does the @faradaym commit in their fork (not submitted as a pull request) resolve this @rolsen @amirna2 or is there a different solution needed?

**Comment by rolsen** [comment]
Yep, @faradaym's commit looks good to me.

Disclaimer: I mentor @faradaym

**Comment by krook** [comment]
Cool. Then it sounds like the next step is to create a pull request then @nfeuer @TimoWielink can review.
