### ISSUE TITLE
Move EEPROM methods out of DuckNet

### ISSUE THREAD

**Issue by TimoWielink** [Call-for-Code/ClusterDuck-Protocol#231]
**Describe the bug**
All the EEPROM methods are built inside of DuckNet since that's where originally passed into the value for the EEPROM. 

**To reproduce**
Open Ducknet.cpp and look at:

`saveWifiCredentials()`
`loadWifiCredentials()`
`saveControlSsis()`
`saveControlPassword`
`loadControlSsis()`
`loadControlPassword`

Move these methods to DuckUtils

**Additional context**
More EEPROM methods are being built now for saving channels, which reminded me of moving them.

**Comment by l-monninger** [comment]
I'm new to the project. These seems like a pretty mellow first contribution. Is this still needed?

**Comment by nfeuer** [comment]
Hi @l-monninger, sorry for the delay! Yes this is still a need!

**Comment by nfeuer** [comment]
Sure! You can join our slack if you need any help www.project-owl.com/slack
