### ISSUE TITLE
Can ClusterDuck.h/.cpp be removed?

### ISSUE THREAD

**Issue by rolsen** [Call-for-Code/ClusterDuck-Protocol#236]
The ClusterDuck class doesn't appear to be used anywhere.

**Comment by nfeuer** [comment]
The ClusterDuck class is leftover from v1 and I don't believe has any function that isn't already in there

**Comment by krook** [comment]
Is there a test that can verify functionality doesn't change before and after?

**Comment by nfeuer** [comment]
This has been addressed in the most recent merge
