### ISSUE TITLE
New TBeam Drivers for Mac

### ISSUE THREAD

**Issue by nfeuer** [Call-for-Code/ClusterDuck-Protocol#242]
**Describe the bug**
Not able to upload code to TBeams with new USB hardware. Silicon Labs driver no longer works.

**To reproduce**
Plug in latest TBeam version and check ports. Instead of showing Silicon Labs it shows something different.

**Expected behavior**
Port should show serial to upload to

**Screenshots**

**Desktop (please complete the following information):**
- Mac

**Additional context**
There is a driver that can be downloaded that works on Big Sur

**Comment by TimoWielink** [comment]
I updated the WiKi to list the new USB drivers
