### ISSUE TITLE
MAX_MUID_PER_ACK not correct

### ISSUE THREAD

**Issue by eydonmlau** [Call-for-Code/ClusterDuck-Protocol#258]
Hi,
    CDP is a great project
In Version 3.0.2
https://github.com/Call-for-Code/ClusterDuck-Protocol/blob/241b509ed992894fef607bb0904dd7d67d23800d/src/CdpPacket.h#L53
`Maximum number of DUID/MUID pairs is:
  floor( (maximum data payload size - N) / (DUID size + MUID size) )
Which is:
  floor( (180 - 1) / 12 ) = 14`
    I think maximum is no longer 180, but 229 while using bloom filter instead of  using path?

**Comment by nfeuer** [comment]
Thanks! Will add this to the upcoming patch

**Comment by nfeuer** [comment]
This is has been included in this patch
