### ISSUE TITLE
Make the Build-a-Duck documentation platform independent

### ISSUE THREAD

**Issue by krook** [Call-for-Code/ClusterDuck-Protocol#49]
Per the conversation on #47 

FYI @gozu42 @Salzi 

![image](https://user-images.githubusercontent.com/1499840/81503247-89adf580-92b0-11ea-9509-7cda3a993bad.png)

![image](https://user-images.githubusercontent.com/1499840/81503265-a2b6a680-92b0-11ea-984a-098de77e9a1a.png)

**Comment by nfeuer** [comment]
We have taken out the manual from the repo and transferred it to the Wiki
