### ISSUE TITLE
improved duck telemetry

### ISSUE THREAD

**Issue by gozu42** [Call-for-Code/ClusterDuck-Protocol#53]
**Is your feature request related to a problem? Please describe.**
currently the alive-quacks do not have any real information content.
there also is no real "monitoring of duck health" beyond it.

**Describe the solution you'd like**
i would like to add some telemetry info to the alive quacks.

* basic - device independent infos (only depends on arduino framework)
* * uptime (millis())
* * loopcount (have a counter at the beginning of loop(), this is a simple way to measure how "busy" an arduino device is)
* * memory stats (free mem, max block, low water mark,...)

* advanced - device specific infos (needs to be part of a board definition)
* * battery level (adc pin)
* * power stats (axp192 on the newer t-beams)

these could all be added in simple string format as space-separated tag=value pairs to the alive message.

**Describe alternatives you've considered**
this could be done in a separate "telemetry quack" message, but i do not see the advantage over just sending it as part of / replacement for the alive-quack.
the text-format is not important to me, if there is an advantage for dms/backend in making the telemtry json right away, just holler.
something like the loopcount is "more natural" to do in the duck-app-sketch, but can also be contained inside the duck-class.

**Additional context**
the basic infos have very low merge-conflict potential since it mainly just changes the alive function.
i would like some basic feedback on format and suggestions for other infos to include.
advanced infos can be added later once it is more obivous how/which boards are supported/used.

**Comment by Evilgeniusnerd** [comment]
@tqrahman  maybe should update this with your ongoing efforts?

**Comment by tqrahman** [comment]
yeah so far we have GPS, Altitude, Board Temperature, Volts, isCharging for the TBeam.

**Comment by nfeuer** [comment]
This has been completed, just need to add memory free

**Comment by nfeuer** [comment]
With the recent merge we were able to provide almost half of these data points

**Comment by nfeuer** [comment]
Created new issue #241
