### ISSUE TITLE
Make CDP Board Independent

### ISSUE THREAD

**Issue by nfeuer** [Call-for-Code/ClusterDuck-Protocol#62]
Currently, the CDP only supports ESP32 and is hardcoded to work with the SX1276 LoRa radio. While this system works well so far, we envision the CDP integrating on a large family of devices. We see other technologies offering CDP compatibility and potentially as a standard used in the future. This flexibility allows for more use cases and a wider range of operation. 

The [RadioLib](https://github.com/jgromes/RadioLib) library currently supports many different radios. However, the current CDP doesn’t make it that easy to switch between different architectures/modules. It was suggested that it might be easier to have a separate configuration file. If going down this route, it would be ideal to keep the configuration file out of the library folder if possible to make editing easier. Another idea to make configuration easier is by adding `#defines` for other development board profiles. 

Hardcoded radio setting areas in `ClusterDuck.cpp`: Line 8, 79, 84, 89, 94, and 99.

Next steps:

- [x] Supporting more of the radio modules supported by the RadioLib

- [x] Creating a configuration file

If there is a radio that is not supported by RadioLib, please create a new issue and link it to this one.

**Comment by gozu42** [comment]
>  Supporting more of the radio modules supported by the RadioLib

do you have any particular radio modules (or even boards with different radio modules) in mind for this?

for the moment i am playing duck-pokemon and adding definitions for every esp32+lora board i can get a sample of.
