### ISSUE TITLE
DuckLink Positioning System (DPS)

### ISSUE THREAD

**Issue by tqrahman** [Call-for-Code/ClusterDuck-Protocol#89]
We are developing the DPS which locates lost Ducks in unknown locations. It calculates the location of a lost Duck using RSSI of Ducks stationed in known locations. (If a lost Duck receives a high RSSI, then that means it is close to that stationed Duck. If the RSSI is low then it is far away from the stationed Duck.)

Currently we have a vanilla firmware to deploy the DPS. Now we have to integrate the firmware into the CDP. For more details on DPS, [check the DPS wiki].

[check the DPS wiki]: <https://github.com/Code-and-Response/ClusterDuck-Protocol/wiki/DuckLink-Positioning-System-(DPS)>

**Comment by nfeuer** [comment]
Lets build a project around this so we can get this out there more.

**Comment by nfeuer** [comment]
Lets move this to CDP Roadmap
